version: '3.8'

services:
  nr6-animations:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "8080:1234"
    command: ["yarn", "run", "dev"]